# These are supported funding model platforms

patreon:  # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
github: [ivankatliarchuk,cloudkats]
patreon: cloudkats
otechie: cloudkats
custom: https://paypal.me/ivankatliarchuk
liberapay: cloudkats
issuehunt: ivankatliarchuk
