
CPUCOUNT = "1"
RAM = "4096"

Vagrant.configure("2") do |config|
  config.vm.hostname    = "dev-box-ubuntu"
  config.vm.box         = "cloudkats/dev-box-ubuntu"
  config.vm.box_version = "2020.05.30"
  config.ssh.extra_args = ["-t", "cd /vagrant; direnv allow; bash --login"]

  if Vagrant.has_plugin?('vagrant-vbguest') then
    config.vbguest.auto_update = true
  else
    config.vagrant.plugins = ['vagrant-vbguest']
  end

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  else
    config.vagrant.plugins = ['vagrant-cachier']
  end

  config.vm.network :private_network, ip: "192.168.33.10"
  config.vm.network :forwarded_port, guest: 9090, host: 9090

  config.vm.provider :virtualbox do |v, override|
    v.name   = "dev-box-ubuntu"
    v.gui    = false
    v.memory = "#{RAM}"
    v.cpus   = "#{CPUCOUNT}"

    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    v.customize ["modifyvm", :id, "--accelerate3d", "off"]
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--vram", "32"]
    v.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end


  config.vm.post_up_message="Setup complete `vagrant ssh` to ssh into the box"

end
