name: validate
# This workflow is triggered on pushes to the repository.
on: [push, pull_request, issues]

jobs:
  docs:
    name: Pre-Commit-Hook
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, 'skip') && contains(github.event.head_commit.message, 'validate')"
    steps:
      - uses: actions/checkout@master
      - name: Install Deps
        run: |
          brew install pre-commit terraform-docs terraform tflint
      - name: Check All Files
        run: |
          pre-commit run --all-files
